name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions: 
      contents: write
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      
      #- name: Update theme
      #  # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
      #  run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.110.0"

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          #personal_token: ${{ secrets.DIEGO_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          #   keep_files: true
          #publish_branch: master
          #cname: example.com
